const { auth, requireRole } = require("../middleware/auth");
const express = require("express");
const controller = require("../controllers/offerings");
const router = express.Router();
router.use(auth);
router.get("/", requireRole("advisor", "student"), controller.list);
router.post("/", requireRole("advisor"), controller.create);
router.patch("/:id", requireRole("advisor"), controller.update);
router.delete("/:id", requireRole("advisor"), controller.remove);
module.exports = router;
