const { auth, requireRole, requireOwnStudent } = require("../middleware/auth");
const express = require("express");
const controller = require("../controllers/students");
const router = express.Router();
router.use(auth);
router.get("/", requireRole("advisor", "admin"), controller.list);
router.get("/:id/record", requireOwnStudent, controller.record);
router.get("/:id/eligible", requireRole("advisor"), controller.eligible);
router.get("/:id", requireOwnStudent, controller.detail);
module.exports = router;
